### ISSUE TITLE
When notifications are clicked, the wrong notes are opened

### ISSUE THREAD

**Issue by tasn** [orgzly/orgzly-android#281]
Hi,

# Reproduce
Have a few notifications (reminders) open for some overdue tasks.
Click on one of them.

# Expected
The edit window for the clicked task should open

# Actual
Quite consistently, the edit page for a different task is opened.

I have a few open, and they are usually open for a few days. Just from observing the behaviour, it looks like it just always opens the same one instead of the correct one. I may be wrong.
Since I'm the first one reporting this, I assume it doesn't happen under normal circumstances and only when you have a few notifications open over the span of a few days.

Please try it, and let me know if you need any more info.

**Comment by licaon-kter** [comment]
I think I saw this too, but I was unable to repro it consistently.

**Comment by tasn** [comment]
Without looking at the code, just based on what class of issues it looks like, I'd assume the notifications have a "task id" associated with them to know which task to open (this is how this would normally be implemented). The issue is probably that the task id is not a uuid or another constant id, but rather something like a line number in the org file (if this is the representation). This means that when the file changes (tasks are added/removed) the ids no longer match.
One way to fix it would be to assign a uuid to be used by orgzly. Another would be to hash the line and use that as an id.

Assuming I'm guessing correctly, this should be fairly easy to detect (and solve).

> I think I saw this too, but I was unable to repro it consistently.

This would also explain why it's not consistent for you. You probably don't leave notifications open long enough for the order of tasks to change.


Let's hope I'm right and it's easy. :)

**Comment by nevenz** [comment]
What version of Orgzly is that?

We had this (presumably) fixed in #214 for 1.6.1.

**Comment by tasn** [comment]
Sorry, forgot to mention that. It's the latest on F-Droid, which is v1.6.1.
Also sorry for not finding that ticket, I was searching for "notifications", and that ticket doesn't include that word. :)

Thanks for fixing it. Let's consider this fixed for now. I'll reopen if I still get it with v1.6.1.

**Comment by nevenz** [comment]
> It's the latest on F-Droid, which is v1.6.1.

You mean v1.6? I don't know why is that...

**Comment by tasn** [comment]
Sorry, obviously, yeah. Long day. Sorry.

I think they are having issues with builds. I'm having issues with EteSync
too.

**Comment by tasn** [comment]
It seems like the solution (workaround) is to release a new version (tag).

Worth trying.

**Comment by nevenz** [comment]
v1.6.2 is out just now, we'll see what happens.

**Comment by tasn** [comment]
Great. Thanks!
